name: Reusable GitOps Pipeline

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      REGISTRY_TOKEN:
        required: true
      GH_BOT_TOKEN:
        required: true

jobs:
  build-and-scan:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Build Docker Image
        run: docker build -t ${{ inputs.image }} .
        
      - name: Log in to DockerHub
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login -u "eriknazaryan" --password-stdin
        
      - name: Push Docker Image
        run: docker push ${{ inputs.image }}

      - name: Run Trivy Security Scanner (Gate)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image }}
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: '1' # 🛑 Բլոկում է փայփլայնը, եթե խոցելիություն կա

  bump-chart:
    needs: build-and-scan
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_BOT_TOKEN }} # 🤖 Պետք է հետ push անելու համար
          
      - name: Update Helm Chart Tag
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          sed -i '' "s/tag:.*/tag:\ \"$SHORT_SHA\"/g" genesis-chart/values.yaml
          
      - name: Commit and Push Back (GitOps Loop)
        run: |
          git config user.name "Genesis CI Bot"
          git config user.email "ci-bot@genesis.com"
          git add genesis-chart/values.yaml
          git commit -m "ci: update genesis image tag [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}